import os
import pathlib

CONFIG_NAME = '.config_application'

f = open(CONFIG_NAME, 'w')

HOME_DIRECTORY = str(pathlib.Path.home())
f.write('HOME_DIRECTORY='+HOME_DIRECTORY+'\n')

NAME_OF_APPLICATION_DATA_DIRECTORY = 'Lotos_Application_Data'
APPLICATION_DATA_DIRECTORY = os.path.join(HOME_DIRECTORY, NAME_OF_APPLICATION_DATA_DIRECTORY)
f.write('APPLICATION_DATA_DIRECTORY='+APPLICATION_DATA_DIRECTORY+'\n')

if not os.path.exists(APPLICATION_DATA_DIRECTORY):
    os.mkdir(APPLICATION_DATA_DIRECTORY)

NAME_OF_ALIGNMENTS_DATA_DIRECTORY = 'Alignments'
ALIGNMENTS_DATA_DIRECTORY = os.path.join(APPLICATION_DATA_DIRECTORY, NAME_OF_ALIGNMENTS_DATA_DIRECTORY)
f.write('ALIGNMENTS_DATA_DIRECTORY='+ALIGNMENTS_DATA_DIRECTORY+'\n')

if not os.path.exists(ALIGNMENTS_DATA_DIRECTORY):
    os.mkdir(ALIGNMENTS_DATA_DIRECTORY)

NAME_OF_FASTA_FILES_DIRECTORY = 'Fasta'
FASTA_FILES_DIRECTORY  = os.path.join(APPLICATION_DATA_DIRECTORY, NAME_OF_FASTA_FILES_DIRECTORY)
f.write('FASTA_FILES_DIRECTORY='+FASTA_FILES_DIRECTORY+'\n')

if not os.path.exists(FASTA_FILES_DIRECTORY):
    os.mkdir(FASTA_FILES_DIRECTORY)

NAME_OF_PDB_FILES_DIRECTORY = 'PDB'
PDB_FILES_DIRECTORY  = os.path.join(APPLICATION_DATA_DIRECTORY, NAME_OF_PDB_FILES_DIRECTORY)
f.write('PDB_FILES_DIRECTORY='+PDB_FILES_DIRECTORY+'\n')

if not os.path.exists(PDB_FILES_DIRECTORY):
    os.mkdir(PDB_FILES_DIRECTORY)

NAME_OF_TEXTUAL_REPORTS_DIRECTORY = 'Textual_reports'
TEXTUAL_REPORTS_DIRECTORY = os.path.join(APPLICATION_DATA_DIRECTORY, NAME_OF_TEXTUAL_REPORTS_DIRECTORY)
f.write('TEXTUAL_REPORTS_DIRECTORY='+TEXTUAL_REPORTS_DIRECTORY+'\n')

if not os.path.exists(TEXTUAL_REPORTS_DIRECTORY):
    os.mkdir(TEXTUAL_REPORTS_DIRECTORY)

NAME_OF_GRAPHIC_VISUALISATIONS_DIRECTORY = 'Visualisations'
GRAPHIC_VISUALISATIONS_DIRECTORY = os.path.join(APPLICATION_DATA_DIRECTORY, NAME_OF_GRAPHIC_VISUALISATIONS_DIRECTORY)
f.write('GRAPHIC_VISUALISATIONS_DIRECTORY='+GRAPHIC_VISUALISATIONS_DIRECTORY+'\n')

if not os.path.exists(GRAPHIC_VISUALISATIONS_DIRECTORY):
    os.mkdir(GRAPHIC_VISUALISATIONS_DIRECTORY)



